version: "3.8"

services:
  redis:
    image: redis:alpine
    container_name: limitly-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  backend:
    build: ./Backend
    container_name: limitly-backend
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - REDIS_URL=redis://redis:6379
      - JWT_SECRET=${JWT_SECRET:-my_super_secret_key_123}
      - MONGO_URI=${MONGO_URI}
      - FRONTEND_URL=http://localhost:5173
    depends_on:
      - redis
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend
      args:
        - VITE_API_URL=http://localhost:3000
    container_name: limitly-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  redis_data:
